version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mynetwork

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodbdata:
