version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - addressbook-data:/var/lib/postgresql/data
      - ./data/people.sql:/docker-entrypoint-initdb.d/people.sql

  addressbook:
    build: src
    environment:
      DB_SCHEMA: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  addressbook-data:
  